import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import Link from "next/link";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body style={{ margin: 0, fontFamily: "Arial, sans-serif" }}>
        <nav
          style={{
            padding: 16,
            borderBottom: "1px solid #ddd",
            display: "flex",
            gap: 16,
          }}
        >
          <Link href="/">Start</Link>
          <Link href="/sattelbestellung">Sattelbestellung</Link>
          <Link href="/fotos">Fotos</Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
